In [1]:
import numpy as np

In [2]:
lst = [1,2,3]
np.array(lst)

array([1, 2, 3])

In [22]:
my_list = np.arange(10, 100, 1)
my_list

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [23]:
my_list.shape

(90,)

In [24]:
my_list.dtype

dtype('int32')

In [29]:
my_list.reshape(3, 30) # 90 = 30 * 3 or 45* 2 or 9 * 10

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
        86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [17]:
shape = (3, 10)
lst = np.zeros(shape)
lst

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
lst.shape

(3, 10)

In [14]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.ones((2,4)) * 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [21]:
arr = [
    [1,2, 3 ],
    [1,5, 5 ]
]
np.array(arr)

array([[1, 2, 3],
       [1, 5, 5]])

## Operation

In [31]:
ones = np.ones(10)
ones


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
ones + 10

array([11., 11., 11., 11., 11., 11., 11., 11., 11., 11.])

In [37]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
ones.dtype

dtype('float64')

In [39]:
ones.astype('int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
str_one = ones.astype(str)
str_one

array(['1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0',
       '1.0'], dtype='<U32')

In [46]:
np.char.add(str_one, "Hello")

array(['1.0Hello', '1.0Hello', '1.0Hello', '1.0Hello', '1.0Hello',
       '1.0Hello', '1.0Hello', '1.0Hello', '1.0Hello', '1.0Hello'],
      dtype='<U37')

## Indexing and Slicing

In [51]:
arr = np.arange(10, 100, 1)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [52]:
arr[0]

10

In [53]:
arr[10: 20] # exlude 20th 

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
arr[89]

99

In [62]:
arr[0: 10: 2]

array([10, 12, 14, 16, 18])

In [67]:
two_d_arr = np.arange(0, 100, 1).reshape(10, 10)
two_d_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [68]:
two_d_arr[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
two_d_arr[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [74]:
two_d_arr[:, 0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [76]:
two_d_arr[1:5]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [81]:
two_d_arr[0:10, 0:2]

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41],
       [50, 51],
       [60, 61],
       [70, 71],
       [80, 81],
       [90, 91]])

In [84]:
two_d_arr[:, ::2]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

## filter and reassign 

In [90]:
two_d_arr = np.arange(0, 100, 1).reshape(10, 10)
two_d_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [87]:
two_d_arr> 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [91]:
two_d_arr[two_d_arr> 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [92]:
new_arr = two_d_arr.copy()

In [93]:
new_arr[two_d_arr> 50] = 500
new_arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50, 500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500, 500]])

In [94]:
two_d_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## Iteration

In [104]:
two_d_arr = np.arange(0, 16, 1).reshape(4, 4)
two_d_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
for r in two_d_arr:
    print(f"Row => {r}")

Row => [0 1 2 3]
Row => [4 5 6 7]
Row => [ 8  9 10 11]
Row => [12 13 14 15]


In [106]:
for r in two_d_arr:
    for c in r:
        print(f"Cell => {c}")

Cell => 0
Cell => 1
Cell => 2
Cell => 3
Cell => 4
Cell => 5
Cell => 6
Cell => 7
Cell => 8
Cell => 9
Cell => 10
Cell => 11
Cell => 12
Cell => 13
Cell => 14
Cell => 15


In [109]:
for r in two_d_arr.T:
    print(f"Row => {r}")

Row => [ 0  4  8 12]
Row => [ 1  5  9 13]
Row => [ 2  6 10 14]
Row => [ 3  7 11 15]


### Enumerate

To get the index/step in loop


In [114]:
for ind, r in enumerate(two_d_arr):
    if ind != 2:
        print(f"Row => {r}")
    else:
        print(f"Row index 2 => {r}")

Row => [0 1 2 3]
Row => [4 5 6 7]
Row index 2 => [ 8  9 10 11]
Row => [12 13 14 15]


## Unpack

In [115]:
for r in two_d_arr:
    print(f"Row => {r}")

Row => [0 1 2 3]
Row => [4 5 6 7]
Row => [ 8  9 10 11]
Row => [12 13 14 15]


In [119]:
for r in two_d_arr:
    print(f"c1 =====>{r[0]}, c2 ======> {r[1]}, c3 =====>{r[2]}, c4 ======> {r[3]}")

c1 =====>0, c2 ======> 1, c3 =====>2, c4 ======> 3
c1 =====>4, c2 ======> 5, c3 =====>6, c4 ======> 7
c1 =====>8, c2 ======> 9, c3 =====>10, c4 ======> 11
c1 =====>12, c2 ======> 13, c3 =====>14, c4 ======> 15


In [118]:
for c1, c2, c3, c4 in two_d_arr:
    print(f"c1 =====>{c1}, c2 ======> {c2}, c3 =====>{c3}, c4 ======> {c4}")

c1 =====>0, c2 ======> 1, c3 =====>2, c4 ======> 3
c1 =====>4, c2 ======> 5, c3 =====>6, c4 ======> 7
c1 =====>8, c2 ======> 9, c3 =====>10, c4 ======> 11
c1 =====>12, c2 ======> 13, c3 =====>14, c4 ======> 15


## Zip

In [127]:
row_named = ["First", "Second", "Third", "Forth"]

In [128]:
for name, r in zip(row_named, two_d_arr):
    print(f"{name} Row => {r}")

First Row => [0 1 2 3]
Second Row => [4 5 6 7]
Third Row => [ 8  9 10 11]
Forth Row => [12 13 14 15]


In [129]:
for index, r in enumerate(two_d_arr):
    print(f"{row_named[index]} Row => {r}")

First Row => [0 1 2 3]
Second Row => [4 5 6 7]
Third Row => [ 8  9 10 11]
Forth Row => [12 13 14 15]
